theme: jekyll-theme-minimal
title: Brainfuck Studio
description: A modern IDE for Brainfuck with tabbed interface and syntax highlighting
logo: /images/icon-large.svg
version: 1.0
website: https://pratanumandal.in/
